-- =============================================================================
-- email_templates: pricing + clinic phone alignment
--
-- ORIGINAL PURPOSE: Update existing email_templates rows with new pricing
-- ($99 -> $79 Wellness Assessment) and new clinic phone numbers.
--
-- 2026-05-17: Neutralized during Lovable Cloud -> direct Supabase migration.
-- This migration's REPLACE-heavy UPDATEs had multiple paren count bugs
-- (10 opens / 9 closes mismatches) that prevented it from running cleanly
-- against a fresh database.
--
-- In a fresh database, the UPDATEs affect zero rows because email_templates
-- is empty. Real template content lands via later seed migrations or via
-- the admin UI post-launch.
--
-- POST-LAUNCH TODO: Verify that all email templates in admin UI have:
--   * $79 Wellness Assessment (not $99 Discovery Consultation or $149 Strategy)
--   * Phone (706) 760-3470 (not 706-922-7454 or 706-973-3866)
--   * In-office LabCorp draw language (not "at-home collection kit")
--   * "Wellness Assessment" terminology (not "Discovery Consultation")
-- =============================================================================

SELECT 1 AS migration_neutralized;
